net start MSSQLSERVER
net start SQLWriter

net stop OracleVssWriterSYMPHONY
net stop OracleDBConsoleSYMPHONY
net stop OracleJobSchedulerSYMPHONY
net stop OracleServiceSYMPHONY
net stop OracleOraDb11g_home1TNSListener